### ISSUE TITLE
CI for NPR_lp.R for bias/se < 2?

### ISSUE THREAD

**Issue by paulgp** [kolesarm/RDHonest#2]
Hi Michal,

I'm not sure if this is intentional, but in NPR_lp.R, when constructing the CI, it's coded as:

`lower <- r1$estimate - bias - stats::qnorm(1-alpha)*sd`
`upper <- r1$estimate + bias + stats::qnorm(1-alpha)*sd`
but isn't this only approximately right for bias/sd >= 2? (According to Table Note 1 from your QE paper with Tim).

Thanks!

**Comment by kolesarm** [comment]
For one-sided confidence intervals, this is correct for whatever the bias-standard deviation ratio is (note `upper` is the upper endpoint of a one-sided CI of the form `(-inf, upper]`, and similarly for `lower`).

Two-sided CIs are constructed as `c(r1$estimate-r1$hl, r1$estimate+r1$hl)`. Here the half-length `hl` takes into account the bias-sd ratio, it is defined as the standard deviation times the critical value from Table 1 in the QE paper
